scr/dashboard/urls.py
from django.urls import path
from .views import index

app_name="dashboard"
urlpatterns = [
    path('', index, name="index"),
]

scr/rapport/urls.py
from django.urls import path
from .views import index

app_name="rapport"
urlpatterns = [
    path('', index,name="index"),
]

scr/student/urls.py
from django.urls import path
from .views import index
from .views import add
from .views import update
from .views import delete

app_name="student"
urlpatterns = [
    path('', index,name="index"),
    path('add',add,name="add"),
    path('update/<int:id>',update,name="update-student"),
    path('delete/<int:id>',delete,name="delete-student"),
]

scr/teacher/urls.py
from django.urls import path
from .views import index
from .views import add
from .views import update
from .views import delete

app_name="teacher"
urlpatterns = [
    path('', index,name="index"),
    path('add',add,name="add"),
    path('update/<int:id>',update,name="update-teacher"),
    path('delete/<int:id>',delete,name="delete-teacher"),
]

scr/user/urls.py
from django.urls import path
from .views import index
from .views import add
from .views import update
from .views import delete

app_name="user"
urlpatterns = [
    path('', index,name="index"),
    path('add',add,name="add"),
    path('update/<int:id>',update,name="update-user"),
    path('delete/<int:id>',delete,name="delete-user"),
]

scr/website/urls.py
from django.contrib import admin
from django.urls import include, path
from student.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/',include("student.urls")),
    path('dashboard/',include("dashboard.urls")),
    path('user/',include("user.urls")),
    path('teacher/',include("teacher.urls")),
    path('rapport/',include("rapport.urls")),
]

scr/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mon Etab - utilisateurs</title>
    <link
      href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body class="bg-gray-100 font-sans antialiased">
    <div class="flex min-h-screen">
      <!-- Sidebar -->
      <aside class="w-64 bg-gray-800 text-white flex flex-col justify-between">
        <div class="p-6">
          <h2 class="text-3xl font-semibold text-center mb-8">Mon Etab</h2>
          <nav>
            <ul>
              <li class="mb-4">
                <a href="{% url 'dashboard:index' %}" class="hover:text-gray-400">Tableau de bord</a>
              </li>
              <li class="mb-4">
                <a
                  href="{% url 'student:index' %}"
                  class="text-blue-400 hover:text-blue-500 font-medium"
                  >Elève</a
                >
              </li>
              <li class="mb-4">
                <a href="{% url 'teacher:index' %}" class="hover:text-gray-400">Professeurs</a>
              </li>
              <li class="mb-4">
                <a href="{% url 'user:index' %}" class="hover:text-gray-400">Utilisateurs</a>
              </li>
              <li class="mb-4">
                <a href="{% url 'rapport:index' %}" class="hover:text-gray-400">Rapport</a>
              </li>
            </ul>
          </nav>
        </div>
        <div class="p-6">
          <a
            href="#"
            class="text-gray-400 hover:text-white flex items-center justify-center"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5 mr-2"
              viewBox="0 0 20 20"
              fill="currentColor"
            >
              <path
                fill-rule="evenodd"
                d="M7 10V4a3 3 0 016 0v6a3 3 0 11-6 0z"
                clip-rule="evenodd"
              />
              <path
                fill-rule="evenodd"
                d="M5 9a2 2 0 100-4 2 2 0 000 4zm10-2a2 2 0 110 4 2 2 0 010-4zm-2 8v2a3 3 0 01-6 0v-2a2 2 0 11-4 0v2a5 5 0 0010 0v-2a2 2 0 11-4 0z"
                clip-rule="evenodd"
              />
            </svg>
            Déconnexion
          </a>
        </div>
      </aside>

      <!-- Main Content -->
      
      {% block content %}

      {% endblock content %}

    </div>
  </body>
</html>