scr/teacher/urls.py
from django.urls import path
from .views import index
from .views import add
from .views import update
from .views import delete

app_name="teacher"
urlpatterns = [
    path('', index,name="index"),
    path('add',add,name="add"),
    path('update/<int:id>',update,name="update-teacher"),
    path('delete/<int:id>',delete,name="delete-teacher"),
]

scr/user/urls.py
from django.urls import path
from .views import index
from .views import add
from .views import update
from .views import delete

app_name="user"
urlpatterns = [
    path('', index,name="index"),
    path('add',add,name="add"),
    path('update/<int:id>',update,name="update-user"),
    path('delete/<int:id>',delete,name="delete-user"),
]

scr/website/urls.py
from django.contrib import admin
from django.urls import include, path
from student.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/',include("student.urls")),
    path('dashboard/',include("dashboard.urls")),
    path('user/',include("user.urls")),
    path('teacher/',include("teacher.urls")),
    path('rapport/',include("rapport.urls")),
]

scr/teacher/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    GENDER_CHOICES = (
        ('h','Homme'),
        ('f','Femme'),
    )
    MATIERE_CHOICES = (
        ('MATH','MATH'),
        ('PHYSIQUE','PHYSIQUE'),
        ('SVT','SVT'),
        ('FRANCAIS','FRANCAIS'),
        
    )
    nom = models.CharField(max_length=15)
    prenoms = models.CharField(max_length=50)
    genre = models.CharField(max_length=20)
    dateNaissance = models.DateField()
    matiere= models.CharField(max_length=20,choices=MATIERE_CHOICES)
    telephone=models.CharField(max_length=30)


    def __str__(self) :
        return self.nom   #super().__str__()
    

scr/teacher/forms.py
from django import forms
from .models import Teacher

class TeachFoM(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = "__all__"
        widgets={
            'dateNaissance':forms.DateInput(attrs={'type':'date'}),
            'genre' :forms.RadioSelect(choices=Teacher.GENDER_CHOICES),
        }

scr/teacher/views.py
from django.shortcuts import render, redirect
from .forms import TeachFoM
from .models import Teacher
# Create your views here.

def index(request):
    teachers = Teacher.objects.all()
    context = {
        'teachers': teachers
        }
    
    return render(request, "teacher/index.html", context)

def add(request):
    context={"title":"Ajouter un eleve"}

    if request.method == "POST":
        print(request.POST)
        form = TeachFoM(request.POST)
        context["form"] = form
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect('teacher:index')
        else:
            return render(request,"teacher/add.html")
    
    # context={'teach_form': teach_form}
    form = TeachFoM()
    context["form"] = form

    return render(request,"teacher/add.html",context)

def update(request, id):
    teacher = Teacher.objects.get(id=id)

    context = {"title":"Modifier professeur"}

    if request.method == "POST":
        form = TeachFoM(request.POST, instance=teacher)
        if form.is_valid():
            form.save()
            return redirect('teacher:index')
        
    form = TeachFoM(instance = teacher)

    context["form"] = form
    
    return render(request,"teacher/add.html",context)

def delete(request, id):
    teacher = Teacher.objects.get(id = id)
    teacher.delete()
    return redirect('teacher:index')

scr/templates/teacher/add.html
{% extends 'base.html' %}


{% block content %}
      <!-- Main Content -->
      <div class="flex-1 p-6">
        <a
          href="{% url 'teacher:index' %}"
          class="text-gray-500 hover:text-gray-700 flex items-center mb-6"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5 mr-2"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M15 19l-7-7 7-7"
            />
          </svg>
          Retour
        </a>
        <div class="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-lg">
          <h1 class="text-2xl font-semibold mb-6 text-center">
            {{title}}
          </h1>
          <form action="#" method="POST" class="grid grid-cols-2 gap-6">
            <!-- Champ Nom -->
            {% csrf_token %}
            
            {{form}}
            <!-- Boutons -->
            <div class="col-span-2 flex justify-center space-x-4">
              <a
                href="{% url 'teacher:index' %}"
                type="reset"
                class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded"
              >
                Annuler
              </a>
              <button
                type="submit"
                class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded"
              >
                Enregistrer
              </button>
            </div>
          </form>
        </div>
      </div>
{% endblock content %}

scr/templates/teacher/edit.html
{% extends 'base.html' %}

{% block content %}
    <!-- Main Content -->
      <div class="flex-1 p-6">
        <a
          href="{% url 'teacher:index' %}"
          class="text-gray-500 hover:text-gray-700 flex items-center mb-6"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5 mr-2"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M15 19l-7-7 7-7"
            />
          </svg>
          Retour
        </a>
        <div class="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-lg">
          <h1 class="text-2xl font-semibold mb-6 text-center">
            Modifier le professeur - 738
          </h1>
          <form action="#" method="POST" class="grid grid-cols-2 gap-6">
            <!-- Champ Nom -->
            <div>
              
              <input
                type="text"
                id="nom"
                name="nom"
                value="Kouakou"
                class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              />
            </div>
            <!-- Champ Prénom -->
            <div>
             
              <input
                type="text"
                id="prenom"
                name="prenom"
                value="Flora"
                class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              />
            </div>
            <!-- Champ Genre -->
            <div class="col-span-2">
              
              <div class="mt-1 flex items-center">
                <input
                  type="radio"
                  id="homme"
                  name="genre"
                  value="homme"
                  class="h-4 w-4 text-indigo-600 border-gray-300 focus:ring-indigo-500"
                />
                <label
                  for="homme"
                  class="ml-3 block text-sm font-medium text-gray-700"
                  >Homme</label
                >
                <input
                  type="radio"
                  id="femme"
                  name="genre"
                  value="femme"
                  class="ml-6 h-4 w-4 text-indigo-600 border-gray-300 focus:ring-indigo-500"
                />
                <label
                  for="femme"
                  class="ml-3 block text-sm font-medium text-gray-700"
                  >Femme</label
                >
              </div>
            </div>
            
            <!-- Champ Date de Naissance -->
            <div>
             
              <input
                
                id="date_naissance"
                name="date_naissance"
                value="22/03/1990"
                class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              />
            </div>
            <!-- Champ Classe -->
            <div>
             
              <select
                id="classe"
                name="classe"
                class="mt-1 block w-full p-2 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              >
                
                <option value="Anglais">Anglais</option>
                
              </select>
            </div>
            <!-- Champ Téléphone -->
            <div>
              <label
                for="telephone"
                class="block text-sm font-medium text-gray-700"
                >Téléphone</label
              >
              <input
                type="text"
                id="telephone"
                name="telephone"
                value="0123456789"
                class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              />
            </div>
            <!-- Champ Ville -->
            <div>
             
              <input
                type="text"
                id="ville"
                name="ville"
                value="Bouaké"
                class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              />
            </div>
            <!-- Boutons -->
            <div class="col-span-2 flex justify-center space-x-4">
              <button
                type="reset"
                class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded"
              >
                Annuler
              </button>
              <button
                type="submit"
                class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded"
              >
                Enregistrer
              </button>
            </div>
          </form>
        </div>
      </div>
{% endblock content %}  

scr/templates/teacher/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
      <!-- Main Content -->
      <div class="flex-1 p-6">
        <div class="flex justify-between items-center mb-6">
          <h1 class="text-2xl font-semibold">Professeurs (2)</h1>
          <a
            href="{% url 'teacher:add' %}"
            class="flex items-center text-blue-500 hover:text-blue-700"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5 mr-2"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M12 4v16m8-8H4"
              />
            </svg>
            Nouveau professeur
          </a>
        </div>
        <div class="bg-white p-6 rounded-lg shadow overflow-auto">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Nom
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Prénom
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Matière
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Vacant
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Date de naissance
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  telephone
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Ville
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Actions
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              {% for teacher in teachers %}
              <tr>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.nom}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.prenoms}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.matiere}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.genre}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.dateNaissance}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{teacher.telephone}}</td>
                <td class="px-6 py-4 whitespace-nowrap">Touba</td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <a  href="{% url 'teacher:update-teacher' teacher.id %}"
                    class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-4 rounded"
                  >
                    Modifier
                </a>
                  <button
                    class="bg-red-500 hover:bg-red-600 text-white font-bold py-1 px-4 rounded ml-2"
                  >
                  <a class="button" href="#popup{{teacher.id }}">Supprimer</a>
                  </button>
                </td>
                <div id="popup{{teacher.id }}" class="overlay">
                  <div class="popup">
                    <h2>ATTENTION !!!</h2>
                    <a class="close" href="#">&times;</a>
                    <div class="content">
                      Voulez-vous supprimer cet professeur ?
                      <div>
                        <button>Non</button>
                        <a href="{% url 'teacher:delete-teacher' teacher.id %}">Oui</a>
                      </div>
                    </div>
                  </div>
                </div>
              </tr>
              {% endfor %}
              
            </tbody>
          </table>
        </div>
      </div>
{% endblock content %}