scr/user/urls.py
from django.urls import path
from .views import index
from .views import add
from .views import update
from .views import delete

app_name="user"
urlpatterns = [
    path('', index,name="index"),
    path('add',add,name="add"),
    path('update/<int:id>',update,name="update-user"),
    path('delete/<int:id>',delete,name="delete-user"),
]

scr/website/urls.py
from django.contrib import admin
from django.urls import include, path
from student.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/',include("student.urls")),
    path('dashboard/',include("dashboard.urls")),
    path('user/',include("user.urls")),
    path('teacher/',include("teacher.urls")),
    path('rapport/',include("rapport.urls")),
]

scr/user/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    pseudo = models.CharField(max_length=10,unique=True)
    password = models.CharField(max_length=128)
    creat_at = models.DateField(auto_now_add=True)

    def __str__(self) :
        return self.password   #super().__str__()
    
    

scr/user/forms.py
from django import forms
from .models import User
class UserForm(forms.Form):
   
    Pseudo = forms.CharField(max_length=15)
    MotDePasse = forms.CharField(max_length=50,widget=forms.PasswordInput)
   
class UseFoM(forms.ModelForm):
    class Meta:
        model = User
        fields = ["pseudo","password"]

scr/user/views.py
from django.shortcuts import render, redirect
from .forms import UserForm,UseFoM
from .models import User



# Create your views here.
def index(request):
    users = User.objects.all()
    context = {
        'users': users
    }

    return render(request, "user/index.html",context)

def add(request):
    context={"title":"Ajouter utilisateur"}
     
    if request.method == "POST":
        print(request.POST)
        form = UseFoM(request.POST)
        context["form"] = form
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect('user:index')
        else:
            return render(request,"user/add.html",context)
  
    form=UseFoM()
    context["form"] = form

    return render(request,"user/add.html",context)


def update(request, id):
    # user = get_object_or_404(User,id = id)
    user = User.objects.get(id=id)
 
    context = {
        "title":"Modifier utilisateur"
    }

    if request.method == "POST":
        form = UseFoM(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('user:index')
        
    form = UseFoM(instance = user)

    context["form"] = form

    return render(request,"user/add.html",context)

def delete(request, id):
    user = User.objects.get(id = id)
    user.delete()
    return redirect('user:index')

scr/templates/user/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


 
{% block content %}

      <!-- Main Content -->
      <div class="flex-1 p-6">
        <a
        href="{% url 'user:index' %}"
        class="text-gray-500 hover:text-gray-700 flex items-center mb-6 "
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-5 w-5 mr-2"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M15 19l-7-7 7-7"
          />
        </svg>
        Retour
      </a>
        <div class="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-lg">
          <h1 class="text-2xl font-semibold mb-6 text-center">
            {{title}}
          </h1>
          <form action="" method="POST" class="grid grid-cols-2 gap-6">
            <!-- Champ Nom -->
             {% csrf_token %}

             {{form }}

             <!-- {{user_form}} -->
            <!-- Boutons -->
            <div class="col-span-2 flex justify-center space-x-4">
              <button
                type="reset"
                class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded"
              >
                Annuler
              </button>
              <button
                type="submit"
                class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded"
              >
                Enregistrer
              </button>
            </div>

          </form>
        </div>
{% endblock content %}

scr/templates/user/edit.html
{% extends 'base.html' %}

{% block content %}
      <!-- Main Content -->
      <div class="flex-1 p-6">
        <a
        href="{% url 'user:index' %}"
        class="text-gray-500 hover:text-gray-700 flex items-center mb-6"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-5 w-5 mr-2"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M15 19l-7-7 7-7"
          />
        </svg>
        Retour
      </a>
        <div class="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-lg">
          <h1 class="text-2xl font-semibold mb-6 text-center">
            Modifier l'utilisateur - 45678
          </h1>
          <form action="#" method="POST" class="grid grid-cols-2 gap-6">
            <!-- Champ Nom -->
            <div>
              
              <input
                type="text"
                id="pseudo"
                name="pseudo"
                value="admin"
                class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              />
            </div>
            <!-- Champ mot_de_passe -->
            <div>
              
              <input
                type="text"
                id="mot_de_passe"
                name="mot_de_passe"
                value="ancien mot de passe"
                class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              />
            </div>
            <!-- Champ confirmation mot de passe -->
            <div>
             
              <input
                type="text"
                id="ville"
                name="ville"
                value="Nouveau mot de passe"
                class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              />
            </div>
            <div>
             
              <input
                type="text"
                id="ville"
                name="ville"
                value="Confirmer nouveau mot de passe"
                class="mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              />
            </div>
            <!-- Boutons -->
            <div class="col-span-2 flex justify-center space-x-4">
              <button
                type="reset"
                class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded"
              >
                Annuler
              </button>
              <button
                type="submit"
                class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded"
              >
                Enregistrer
              </button>
            </div>
            </div>
            
            
            
          </form>

{% endblock content %}   

scr/templates/user/index.html
{% extends 'base.html' %}

{% block content%}
      <!-- Main Content -->
      <div class="flex-1 p-6">
        <div class="flex justify-between items-center mb-6">
          <h1 class="text-2xl font-semibold">utilisateurs (2)</h1>
          <a
            href="{% url 'user:add' %}"
            class="flex items-center text-blue-500 hover:text-blue-700"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5 mr-2"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M12 4v16m8-8H4"
              />
            </svg>
            Nouvel utilisateurs
          </a>
        </div>
        <div class="bg-white p-6 rounded-lg shadow overflow-auto">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Pseudo
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Date de création
                </th>
                <th
                  class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Actions
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              {% for user in users %}
              <tr>
                <td class="px-6 py-4 whitespace-nowrap">{{user.pseudo}}</td>
                <td class="px-6 py-4 whitespace-nowrap">{{user.creat_at}}</td>
                
                <td class="px-6 py-4 whitespace-nowrap">
                  <a href="{% url 'user:update-user' user.id %}"
                    class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-4 rounded"
                  >
                    Modifier
                </a>
                <a href="{% url 'user:delete-user' user.id %}"
                    class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-4 rounded"
                  >
                    Supprimer
                </a>
                </td>
              </tr>

              {% endfor %}
              
            </tbody>
          </table>
        </div>
      </div>
{% endblock content %}